
// File generated by Gemini.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAAkDf6w3go0H8nJvOCyYll4pJr_KY82c',
    appId: '1:978242576416:web:c3361d7093a5dac13a9c45',
    messagingSenderId: '978242576416',
    projectId: 'fireflutter-f5972',
    authDomain: 'fireflutter-f5972.firebaseapp.com',
    storageBucket: 'fireflutter-f5972.firebasestorage.app',
    measurementId: 'G-PBVTQHZTK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAAkDf6w3go0H8nJvOCyYll4pJr_KY82c',
    appId: '1:978242576416:android:c3361d7093a5dac13a9c45',
    messagingSenderId: '978242576416',
    projectId: 'fireflutter-f5972',
    storageBucket: 'fireflutter-f5972.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAAkDf6w3go0H8nJvOCyYll4pJr_KY82c',
    appId: '1:978242576416:ios:c3361d7093a5dac13a9c45',
    messagingSenderId: '978242576416',
    projectId: 'fireflutter-f5972',
    storageBucket: 'fireflutter-f5972.firebasestorage.app',
    iosBundleId: 'com.example.gtkflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAAkDf6w3go0H8nJvOCyYll4pJr_KY82c',
    appId: '1:978242576416:macos:c3361d7093a5dac13a9c45',
    messagingSenderId: '978242576416',
    projectId: 'fireflutter-f5972',
    storageBucket: 'fireflutter-f5972.firebasestorage.app',
    iosBundleId: 'com.example.gtkflutter',
  );
}
